#!/usr/bin/env bash

# set -e
# set -x

BUILD_DIR="./build"
SOURCE_DIR="./"

CLEAN_BUILD=0

function cleanEnvioment()
{
  echo " -- Clear enviroment"
  
  [ -d "${BUILD_DIR}" ] && find "${BUILD_DIR}" -delete
}

function installDeps()
{
  conan install . --output-folder="${BUILD_DIR}" --build=missing
}

function conanInfo()
{
  echo "Info: Print file: ./conanfile.txt"
  cat ./conanfile.txt
}

function setupCompilation()
{
  cmake -S${SOURCE_DIR} -B${BUILD_DIR} -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
}

function runCompilation()
{
  cmake --build "${BUILD_DIR}"
}

function showHelp() {
  echo "-h,  --help        show help menu."
  echo "-c,  --clean       run clean build."
  echo "-ci, --conan-info print conan configuration file."
  echo "-V,  --verbose     run script in verbose mode."
}

BASEDIR=$(dirname "$0")
pushd "$BASEDIR"

if [ ! -f ./conanfile.txt ]; then
  echo "Error: The conanfile.txt file doesn't exist"
  exit 1
fi

while [ $# -gt 0 ];
do
  case "$1" in
  -h|--help) 
      showHelp
      exit 0
      ;;
  -c|--clean) 
      shift
      CLEAN_BUILD=1
      ;;

  -ci|--conan-info)
      shift
      conanInfo
      exit 0
      ;;
  --)
      shift
      break;;
  esac
  shift
done

if [[ ${CLEAN_BUILD} == "1" ]]; then
  cleanEnvioment
fi

installDeps

setupCompilation

runCompilation
