#!/usr/bin/env bash

# set -e
# set -x

BUILD_DIR="./build"
SOURCE_DIR="./"

CLEAN_BUILD=0

function cleanEnvioment()
{
  echo " -- Clear enviroment"
  
  [ -d "${BUILD_DIR}" ] && find "${BUILD_DIR}" -delete
}

function installDeps()
{
  conan install . --output-folder="${BUILD_DIR}" --build=missing
}

function setupCompilation()
{
  cmake -S${SOURCE_DIR} -B${BUILD_DIR} -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
}

function runCompilation()
{
  cmake --build "${BUILD_DIR}"
}

function showHelp() {
  echo "-h, --help        show help menu."
  echo "-c, --clean       run clean build."
  echo "-V, --verbose     run script in verbose mode."
}

BASEDIR=$(dirname "$0")
pushd "$BASEDIR"

while [ $# -gt 0 ];
do
  case "$1" in
  -h|--help) 
      showHelp
      exit 0
      ;;
  -c|--clean) 
      CLEAN_BUILD=1
      shift
      ;;
  --)
      shift
      break;;
  esac
  shift
done

if [[ ${CLEAN_BUILD} == "1" ]]; then
  cleanEnvioment
fi

installDeps

setupCompilation

runCompilation
